### ISSUE TITLE
Add uplink field topics support

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/nodered-app-lib#6]
The MQTT broker now published topics for specific fields:
https://github.com/TheThingsNetwork/ttn/tree/refactor/mqtt#uplink-fields

In the node's settings the user should be able to override the default `messages` topic alias (which is `+/devices/+/up`.

**Comment by johanstokking** [comment]
I'd say add the ability to enter an optional field name which is appended to the topic internally

**Comment by FokkeZB** [comment]
I thought of that but then you will not be able to subscribe to a specific device. I already thought of an idea for https://github.com/TheThingsNetwork/node-app-lib/issues/9 which I'll implement next week

**Comment by johanstokking** [comment]
How so? You can subscribe to `+/devices/+/up/{field}`, replacing `{field}` by the entered field name. If no field name is entered, just subscribe to `+/devices/+/up`

**Comment by FokkeZB** [comment]
Both examples are for all devices, not a specific one, which would require the second + to be a device ID

**Comment by FokkeZB** [comment]
Circling back after convo on Slack, for Node-RED the node should have an optional **Device ID** field as well as an optional **Field (Path)**.

If you'd want to listen to a couple of Device ID / Field combos you should use multiple TTN nodes or simply use the MQTT node and go crazy.

**Comment by FokkeZB** [comment]
Can be done once https://github.com/TheThingsNetwork/node-app-lib/pull/18 is merged

**Comment by FokkeZB** [comment]
Closed by #16
