### ISSUE TITLE
Split ttn node into uplink and activations

### ISSUE THREAD

**Issue by romeovs** [TheThingsNetwork/nodered-app-lib#9]
During the workshops, I often see people connecting the second output of the ttn node and expecting uplink messages to come out of that as well.

I think we can alleviate this problem by creating a new node: the ttn activations node.
The client can be shared via the configuration node that is introduced by #8 so this does not
create any configuration / connection overhead.

**Comment by FokkeZB** [comment]
Yes, let's do this and call that node `ttn-activation` (see https://github.com/TheThingsNetwork/nodered-app-lib/pull/8#r79348606)

**Comment by FokkeZB** [comment]
Closed by #16
